name: DockerHub Image CI

on:
    push:
        branches:
            - main

    release:
        types: [published]

jobs:
    build-main:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels)
              id: meta
              run: |
                if [[ "${{ github.event_name }}" == "push" ]]; then
                  echo "TAG_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
                elif [[ "${{ github.event_name }}" == "release" ]]; then
                  echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                fi

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5.1.0
              with:
                platforms: linux/amd64,linux/arm64
                push: true
                tags: makeplane/iframely:${{ env.TAG_NAME }}
              env:
                DOCKER_BUILDKIT: 1
